#!/bin/bash
# vim: set ts=4 sts=4 sw=4 et:

die() {
    echo "$@" >&2
    exit 1
}

# Environment variables
POSTFIX_HOSTNAME="${POSTFIX_HOSTNAME:-rancid.example.com}"
POSTFIX_ORIGIN="${POSTFIX_ORIGIN:-rancid.example.com}"
POSTFIX_RELAYHOST="${POSTFIX_RELAYHOST:-example.com}"
MAIL_RCPT="${MAIL_RCPT:-rancid@example.com}"

# Check that the RANCID software is configured correctly
[[ -f "/etc/rancid/rancid.conf" ]] || die "ERROR: no /etc/rancid/rancid.conf found"
[[ -f "/var/rancid/.cloginrc" ]] || die "ERROR: no /var/rancid/.cloginrc found"

# Generate the Postfix configuration
cat > /etc/postfix/main.cf << EOF
# Taken directly from the "Postfix on a null client" section of:
# http://www.postfix.org/STANDARD_CONFIGURATION_README.html

myhostname = $POSTFIX_HOSTNAME
myorigin = $POSTFIX_ORIGIN
relayhost = $POSTFIX_RELAYHOST

# do not accept mail from the network
inet_interfaces = loopback-only
# disable local mail delivery, all mail goes to the mail server
mydestination =
EOF

# Generate crontab to run RANCID
cat > /etc/cron.d/rancid << EOF
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root
HOME=/var/rancid
# Run config differ hourly
1 * * * * rancid /usr/bin/timeout 30m /usr/bin/rancid-run -m "$MAIL_RCPT"
EOF

# Generate crontab to clean up RANCID log files
cat > /etc/cron.d/rancid-cleanup << EOF
SHELL=/bin/bash
PATH=/sbin:/bin:/usr/sbin:/usr/bin
MAILTO=root
HOME=/var/rancid
# Cleanup log files hourly
1 * * * * rancid /usr/bin/find /var/log/rancid -type f -cmin +120 -delete
EOF

# Make sure RANCID directories have correct permissions
for i in /var/rancid /var/log/rancid ; do
    mkdir -p "$i"
    chown -R rancid:rancid "$i"
done

# Start Postfix mail server
/usr/sbin/postfix start || die "ERROR: postfix failed to start"

# Run rancid-cvs once to make sure source control directories exist
/bin/su -l rancid -c '/usr/bin/rancid-cvs'

# Start crond
exec /usr/sbin/crond -n -x proc
